name: .NET Desktop

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # Для приложений с WinForms/WPF нужен Windows-раннер

    env:
      Solution_Name: FastP.sln
      Test_Project_Path: FastP.Tests/FastP.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Установка .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Create Solution if not exists
      run: |
        if (!(Test-Path FastP.sln)) {
            dotnet new sln -n FastP
            dotnet sln add FastP.csproj
            dotnet sln add FastP.Tests/FastP.Tests.csproj
        }
      shell: powershell

    # Восстановление зависимостей
    - name: Restore dependencies
      run: dotnet restore
      
    # Сборка
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    # Запуск тестов
    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal

