name: .NET Desktop

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch: # Добавляем возможность ручного запуска

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release] # Debug нам для релиза не нужен

    runs-on: windows-latest

    env:
      Solution_Name: FastP.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    # Публикация в один файл (Self-Contained)
    - name: Publish
      run: |
        dotnet publish FastP.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=embedded -o ./publish

    # Загружаем всю папку publish, чтобы не потерять ничего важного
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FastP-Windows-x64
        path: ./publish/*
